name: "Unit tests"

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v5
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: pnpm
      - run: pnpm bootstrap
      - working-directory: ./packages/nocodb-sdk
        run: |
          pnpm run generate:sdk
          pnpm run build:main
      - working-directory: ./packages/nocodb
        run: pnpm run test